# Generated by Django 5.2.17 on 2026-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_description",
                    models.TextField(verbose_name="Описание ресторана"),
                ),
                ("history", models.TextField(verbose_name="История ресторана")),
                ("mission", models.TextField(verbose_name="Миссия ресторана")),
                ("team", models.TextField(verbose_name="Команда")),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="Главное изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент сайта",
                "verbose_name_plural": "Контент сайта",
            },
        ),
    ]
