# Generated by Django 5.2.17 on 2026-09-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_sitecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(
                        upload_to="restaurant/", verbose_name="Изображение"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("restaurant", "Ресторан"),
                            ("team", "Команда"),
                            ("menu", "Меню"),
                        ],
                        max_length=20,
                        verbose_name="Раздел",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение ресторана",
                "verbose_name_plural": "Изображения ресторана",
            },
        ),
    ]
